apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qbrxrbfsb-nodejs 
  janus-idp.io/tekton: qbrxrbfsb-nodejs
  backstage.io/kubernetes-id: qbrxrbfsb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qbrxrbfsb-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  